# Generated by Django 4.2.3 on 2023-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='charge_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Charge_id'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(default='0', max_length=1, verbose_name='Payment Status'),
        ),
    ]
